# TODO: Replace every FILL_ME value with task-specific settings.
TASK_CONFIG = {
    "task_name": "FILL_ME_MANISKILL_TASK_ID",
    "obs_dim": None,
    "action_dim": None,
    "obs_horizon": 2,
    "action_horizon": 8,
    "prediction_horizon": 16,
    "diffusion_train_steps": 100,
    "inference_steps": 12,
    "max_episode_steps": 200,
    "data_dir": "data/NEW_TASK",
    "dataset": "data/FILL_ME/converted_demos.h5",
    "default_models": ["model_a", "model_b"],
    "default_steps": 50000,
    "default_batch_size": 512,
    "default_learning_rate": 1e-4,
    "validation_fraction": 0.1,
    "evaluation_episodes": 256,
    "evaluation_first_seed": 10000,
    "evaluation_envs": 64,
    "eval_backend": "physx_cuda",
    "control_mode": "FILL_ME_CONTROL_MODE",
    "obs_mode": "state",
    "reward_mode": "sparse",
}
