[task]
name = "plugcharger"
env_id = "PlugCharger-v1"
control_mode = "pd_joint_pos"
max_episode_steps = 200

[data]
train_path = "train/PlugCharger-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
val_path = "val/PlugCharger-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
