[task]
name = "pushcube"
env_id = "PushCube-v1"
control_mode = "pd_ee_delta_pos"
max_episode_steps = 100

[data]
train_path = "train/PushCube-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
val_path = "val/PushCube-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
