[task]
name = "stackcube"
env_id = "StackCube-v1"
control_mode = "pd_ee_delta_pos"
max_episode_steps = 200

[data]
train_path = "train/StackCube-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
val_path = "val/StackCube-v1/motionplanning/trajectory.state.{control_mode}.physx_cpu.h5"
