TASK_CONFIG = {
    "task_name": "PlugCharger-v1",
    "obs_dim": 46,
    "action_dim": 7,
    "obs_horizon": 2,
    "action_horizon": 8,
    "prediction_horizon": 16,
    "diffusion_train_steps": 100,
    "inference_steps": 12,
    "max_episode_steps": 200,
    "data_dir": "data/task_06",
    "dataset": "data/task_06/raw/PlugCharger-v1/motionplanning/trajectory.state.pd_ee_delta_pose.physx_cpu.h5",
    "default_models": ["mlp", "unet", "transformer"],
    "default_steps": 50000,
    "default_batch_size": 512,
    "default_learning_rate": 1e-4,
    "validation_fraction": 0.1,
    "evaluation_episodes": 256,
    "evaluation_first_seed": 10000,
    "evaluation_envs": 64,
    "eval_backend": "physx_cuda",
    "control_mode": "pd_ee_delta_pose",
    "obs_mode": "state",
    "reward_mode": "sparse",
}
